version: '3.8'

services:
  passenger-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: okada-passenger-app
    ports:
      - "3000:19000"  # Expo main port
      - "3001:19001"  # Metro bundler
      - "3002:19002"  # Expo development server
    volumes:
      - .:/app
      - /app/node_modules  # Prevents overwriting the container's node_modules
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://backend:3000/api  # Adjust this to match your backend service
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - okada-network

networks:
  okada-network:
    driver: bridge

